### ISSUE TITLE
github3.exceptions.UnprocessableEntity: 422 Validation Failed

### ISSUE THREAD

**Issue by Heier2013** [maguowei/starred#14]
When i run demo script
`starred --repository awesome-stars --sort`
i get this error
``` shell
Traceback (most recent call last):
  File "/usr/local/bin/starred", line 11, in <module>
    sys.exit(starred())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/starred.py", line 87, in starred
    rep = gh.create_repository(repository, 'Awesome List of my own!')
  File "/usr/local/lib/python2.7/site-packages/github3/decorators.py", line 33, in auth_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/github3/github.py", line 348, in create_repository
    json = self._json(self._post(url, data=data), 201)
  File "/usr/local/lib/python2.7/site-packages/github3/models.py", line 154, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/usr/local/lib/python2.7/site-packages/github3/models.py", line 176, in _boolean
    raise exceptions.error_for(response)
github3.exceptions.UnprocessableEntity: 422 Validation Failed
```

BTW,i have already set the `GITHUB_TOKEN`

**Comment by Heier2013** [comment]
I can only use this script update my repository
`starred --username Heier2013  --repository awesome-stars --sort`

Is this a bug or you need update the README.md file?

**Comment by maguowei** [comment]
You need set the --username.
If not set, starred try get `$USER` from environment variable 
please try 
```
starred --username Heier2013  --repository awesome-stars --sort
```

**Comment by maguowei** [comment]
see #15 ,thanks
