### ISSUE TITLE
[BUG] UnicodeEncodeError: (Better to add an option to set output file...)

### ISSUE THREAD

**Issue by zYeoman** [maguowei/starred#17]
Windows Cmd

```
> python starred.py --username zYeoman --sort > TEST.md                                                    
Traceback (most recent call last):                                                                         
  File "starred.py", line 92, in <module>                                                                  
    starred()                                                                                              
  File "C:\Users\zYeoman\Anaconda3\lib\site-packages\click\core.py", line 716, in __call__                 
    return self.main(*args, **kwargs)                                                                      
  File "C:\Users\zYeoman\Anaconda3\lib\site-packages\click\core.py", line 696, in main                     
    rv = self.invoke(ctx)                                                                                  
  File "C:\Users\zYeoman\Anaconda3\lib\site-packages\click\core.py", line 889, in invoke                   
    return ctx.invoke(self.callback, **ctx.params)                                                         
  File "C:\Users\zYeoman\Anaconda3\lib\site-packages\click\core.py", line 534, in invoke                   
    return callback(*args, **kwargs)                                                                       
  File "starred.py", line 78, in starred                                                                   
    click.echo(data)                                                                                       
  File "C:\Users\zYeoman\Anaconda3\lib\site-packages\click\utils.py", line 259, in echo                    
    file.write(message)                                                                                    
UnicodeEncodeError: 'gbk' codec can't encode character '\xe6' in position 55: illegal multibyte sequence   
```

It works after `set PYTHONIOENCODING=utf8``.

**Comment by maguowei** [comment]
Yes, set `PYTHONIOENCODING=UTF-8` when `sys.stdout.encoding` not `utf-8`

ref: http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script
