### ISSUE TITLE
ImportError: cannot import name URITemplate

### ISSUE THREAD

**Issue by FedericoPonzi** [maguowei/starred#18]
Following the istructions, I run pip install starred. When I try to run starred, i get this:

```
$ starred
Traceback (most recent call last):
  File "/usr/local/bin/starred", line 7, in <module>
    from starred import starred
  File "/usr/local/lib/python2.7/dist-packages/starred.py", line 7, in <module>
    from github3 import GitHub
  File "/usr/local/lib/python2.7/dist-packages/github3/__init__.py", line 18, in <module>
    from .api import (
  File "/usr/local/lib/python2.7/dist-packages/github3/api.py", line 11, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/usr/local/lib/python2.7/dist-packages/github3/github.py", line 17, in <module>
    from .gists import Gist
  File "/usr/local/lib/python2.7/dist-packages/github3/gists/__init__.py", line 16, in <module>
    from .gist import Gist
  File "/usr/local/lib/python2.7/dist-packages/github3/gists/gist.py", line 14, in <module>
    from .comment import GistComment
  File "/usr/local/lib/python2.7/dist-packages/github3/gists/comment.py", line 12, in <module>
    from ..users import User
  File "/usr/local/lib/python2.7/dist-packages/github3/users.py", line 13, in <module>
    from uritemplate import URITemplate
ImportError: cannot import name URITemplate
```

**Comment by FedericoPonzi** [comment]
Running:

```
pip unistall uritemplate
pip install uritemplate
```

Resolved the issue.
