### ISSUE TITLE
 execv() arg 2 must contain only strings

### ISSUE THREAD

**Issue by durban89** [maguowei/starred#19]
$ starred --username dapeng --repository awesome-stars --sort
Traceback (most recent call last):
  File "/usr/local/bin/starred", line 11, in <module>
    sys.exit(starred())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in **call**
    return self.main(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, *_ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(_args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/starred.py", line 89, in starred
    click.launch(rep.html_url)
  File "/usr/local/lib/python2.7/site-packages/click/termui.py", line 483, in launch
    return open_url(url, wait=wait, locate=locate)
  File "/usr/local/lib/python2.7/site-packages/click/_termui_impl.py", line 469, in open_url
    return subprocess.Popen(args, stderr=null).wait()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

**Comment by Stenudd** [comment]
Same problem here

**Comment by maguowei** [comment]
paste the result of run  `pip freeze` ?  Did you try install it use virtualenv  or pyvenv(Python3)?

@Stenudd  @zhangda89

**Comment by Stenudd** [comment]
$ pip freeze
APScheduler==3.0.5
BeautifulSoup==3.2.1
CacheControl==0.11.5
capstone==3.0.4
certifi==2015.11.20
cffi==1.5.2
chardet==2.2.1
click==6.6
colorama==0.3.3
cracklib==2.9.1
cryptography==1.1.2
Cython==0.22
distlib==0.2.1
docutils==0.7
enum34==1.0.4
gentoolkit==0.3.0.9.post2
github3.py==1.0.0a4
html5lib==0.9999999
idna==2.0
ipaddress==1.0.14
Jinja2==2.7.3
layman==2.0.0
lockfile==0.11.0
lxml==3.4.1
M2Crypto==0.21.1
Magic-file-extensions==0.2
MarkupSafe==0.23
mercurial==3.3.2
mysql-connector-python==1.0.7
ndg-httpsclient==0.4.0
netlink==1.0
numpy==1.9.0
packaging==15.3
pbr==1.8.1
Pillow==3.1.1
ply==3.6
portage==2.2.26
pprintpp==0.2.3
progress==1.2
protobuf==2.5.0
psycopg2==2.5.3
py==1.4.30
py-bcrypt==0.4
pyalsa==1.0.26
pyasn1==0.1.8
pycparser==2.14
pycurl==7.19.0
pyelftools==0.22
pygame==1.9.2rc0
pygobject==3.18.2
pygraphviz==1.3.1
pylibacl==0.5.0
pyogg==1.3
PyOpenAL==0.1.6
PyOpenGL==3.0.2
pyOpenSSL==0.15.1
Pyrex==0.9.9
pysandbox==1.6
python-ldap==2.3.13
pyvorbis==1.4
pyxattr==0.5.5
pyxdg==0.25
requests==2.8.1
retrying==1.3.3
simplejson==3.6.4
six==1.10.0
starred==1.3.1
tkSnack==2.2.10
uritemplate.py==0.3.0
wxPython==2.8.12.1
wxPython-common==2.8.12.1
yasm==0.0
