### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by pramitbiswas** [maguowei/starred#28]
> (githubStarred) ...\githubStarred>starred --username pramitbiswas --sort > README.md
Traceback (most recent call last):
  File "...\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "...\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "...\githubStarred\githubStarred\Scripts\starred.exe\__main__.py", line 9, in <module>
  File "...\githubstarred\githubstarred\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "...\githubstarred\githubstarred\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "...\githubstarred\githubstarred\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "...\githubstarred\githubstarred\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "...\githubstarred\githubstarred\lib\site-packages\starred.py", line 89, in starred
    click.echo(data)
  File "...\githubstarred\githubstarred\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "...\githubstarred\githubstarred\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 105-112: character maps to <undefined>

**Comment by maguowei** [comment]
#17 this may help.

**Comment by maguowei** [comment]
#17 this may help.
