### ISSUE TITLE
Incompatible with Python 3.10 (ImportError: cannot import name 'Callable' from 'collections')

### ISSUE THREAD

**Issue by almereyda** [maguowei/starred#68]
After upgrading to Fedora 35 with Python 3.10, this module stopped working. Downgrading with help of `pyenv` helped get this into a working condition again. The thrown error reads:

```py
Traceback (most recent call last):
  File "/home/yala/.local/bin/starred", line 5, in <module>
    from starred.starred import starred
  File "/home/yala/.local/lib/python3.10/site-packages/starred/starred.py", line 8, in <module>
    from github3 import GitHub
  File "/home/yala/.local/lib/python3.10/site-packages/github3/__init__.py", line 24, in <module>
    from .api import (
  File "/home/yala/.local/lib/python3.10/site-packages/github3/api.py", line 13, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/home/yala/.local/lib/python3.10/site-packages/github3/github.py", line 10, in <module>
    from . import apps
  File "/home/yala/.local/lib/python3.10/site-packages/github3/apps.py", line 10, in <module>
    from . import models
  File "/home/yala/.local/lib/python3.10/site-packages/github3/models.py", line 13, in <module>
    from . import session
  File "/home/yala/.local/lib/python3.10/site-packages/github3/session.py", line 3, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib64/python3.10/collections/__init__.py)
```

**Comment by maguowei** [comment]
pls use latest version

`pip install starred==4.0.0`
