### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by juev** [maguowei/starred#77]
Hello, thank you for your program. Its awesome!

I used starred many times.
Yesterday I got error: 

```python
Run starred --username juev --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'update stars'
  starred --username juev --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'update stars'
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.1[2](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:2)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:3).7.12/x6[4](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:4)/lib
    GITHUB_TOKEN: ***
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x[6](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:6)4/bin/starred", line 8, in <module>
    sys.exit(starred())
  File "/opt/hostedtoolcache/Python/3.[7](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:7).12/x64/lib/python3.7/site-packages/click/core.py", line 82[9](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:9), in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line [10](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:10)66, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/starred/starred.py", line 72, in starred
    for s in stars:
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/structs.py", line 122, in __iter__
    yield cls(i)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/models.py", line 48, in __init__
    self._update_attributes(json)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/repos/repo.py", line 97, in _update_attributes
    self.owner = users.ShortUser(repo["owner"], self)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/models.py", line 48, in __init__
    self._update_attributes(json)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/github3/users.py", line 3[11](https://github.com/juev/awesome-stars/runs/5715556212?check_suite_focus=true#step:5:11), in _update_attributes
    self.avatar_url = user["avatar_url"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

What's the problem?

As I can see previous we have the same envs:
```python
Run starred --username juev --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'update stars'
  starred --username juev --repository awesome-stars --sort --token ${GITHUB_TOKEN} --message 'update stars'
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.1[2](https://github.com/juev/awesome-stars/runs/5701600079?check_suite_focus=true#step:5:2)/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/[3](https://github.com/juev/awesome-stars/runs/5701600079?check_suite_focus=true#step:5:3).7.12/x6[4](https://github.com/juev/awesome-stars/runs/5701600079?check_suite_focus=true#step:5:4)/lib
    GITHUB_TOKEN: ***
/usr/bin/xdg-open: 8[6](https://github.com/juev/awesome-stars/runs/5701600079?check_suite_focus=true#step:5:6)9: www-browser: not found
/usr/bin/xdg-open: [8](https://github.com/juev/awesome-stars/runs/5701600079?check_suite_focus=true#step:5:8)6[9](https://github.com/juev/awesome-stars/runs/5701600079?check_suite_focus=true#step:5:9): links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'https://github.com/juev/awesome-stars'
```

Thank you!

**Comment by AlexiaChen** [comment]
I incount this error two days ago

**Comment by juev** [comment]
@AlexiaChen if you interested, I wrote starred in go: [starred](https://github.com/juev/starred)

**Comment by AlexiaChen** [comment]
> @AlexiaChen if you interested, I wrote starred in go: [starred](https://github.com/juev/starred)

@juev  Ahhh, Thanks,   This is also workaround.

**Comment by maguowei** [comment]
pls install latest version

`pip install starred==4.0.1`
